---
title: "Session 4 - Final Project"
author: "Daniel Viana"
date: "February 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**a**)

```{r}
#Mpa model
mpa.model = function(f, growth, K, N0, t, d, MPA, L){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
   #MPAs in the middle
  f.patches=rep(f, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.patches[mpa.begin:mpa.end] = 0
  }
  
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Create a vector to store total yield
  total.yield = pop*f.patches
  
  #Create an empty plot to plot the revenue trhough time 
  #plot(NA, NA, ylab="Revenue", xlab="time", ylim=c(0, 100000), xlim=c(0, t))
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    #Immi = c(pop[2]*d/2, c(pop[1:(L-1)]*d/2 + pop[3:L]*d/2), pop[L-1]*d/2)
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #fishing
    fishing = f.patches*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    
  }
  #Create a variable for our resulting population size (all patches in year t)
  sum.pop = sum(pop)
  
  #Create a variable for our resulting yield (all patches in year t)
  sum.yield.eq = sum(fishing)
  
  #Create a variable for our resulting yield accross all years and patches
  sum.yield = sum(total.yield)
  
  #Calculate average population size
  EqB = sum(pop)/L
  
  #return function with main results
  #return(c(sum.pop, sum.yield.eq, sum.yield, NPV, MPA, f, d))
  
  #return function for calculating optimal fishing mortality
  return(sum.yield.eq)
  
  #return function for calculation the open access fishing mortality
  #return(abs(EqB-0.2*K))
  }

#Test our function
res = mpa.model(g=0.5, K=100, N0=50, t=50, MPA=30, L = 100, d=0.2, f=0.4)
res

#Well managed - function needs to return the sum of yield (sum.yield.eq). Here we will maximize the yield by changing the fishing mortality. RMEMBER TO CHANGE YOUR RETURN function. In this case optimal fishing mortality will be f.wm = 0.2531916
p0 = 0.1
fit = optim(p0, mpa.model, method = c("L-BFGS-B"), lower = 0, upper = 1, control= list(fnscale = -1), 
            growth=0.5, K=100, N0=50, t=50, MPA=50, L = 100, d=0.2)

f.wm = fit$par
f.wm
```

```{r}
#Mpa model
mpa.model = function(f, growth, K, N0, t, d, MPA, L){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
   #MPAs in the middle
  f.patches=rep(f, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.patches[mpa.begin:mpa.end] = 0
  }
  
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Create a vector to store total yield
  total.yield = pop*f.patches
  
  #Create an empty plot to plot the revenue trhough time 
  #plot(NA, NA, ylab="Revenue", xlab="time", ylim=c(0, 100000), xlim=c(0, t))
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    #Immi = c(pop[2]*d/2, c(pop[1:(L-1)]*d/2 + pop[3:L]*d/2), pop[L-1]*d/2)
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #fishing
    fishing = f.patches*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    
  }
  #Create a variable for our resulting population size (all patches in year t)
  sum.pop = sum(pop)
  
  #Create a variable for our resulting yield (all patches in year t)
  sum.yield.eq = sum(fishing)
  
  #Create a variable for our resulting yield accross all years and patches
  sum.yield = sum(total.yield)
  
  #Calculate average population size
  EqB = sum(pop)/L
  
  #return function with main results
  #return(c(sum.pop, sum.yield.eq, sum.yield, NPV, MPA, f, d))
  
  #return function for calculating optimal fishing mortality
  #return(sum.yield.eq)
  
  #return function for calculation the open access fishing mortality
  return(abs(EqB-0.2*K))
  }

#Test our function
res = mpa.model(g=0.5, K=100, N0=50, t=50, MPA=30, L = 100, d=0.2, f=0.4)
res

##Find open access fishing mortality - function needs to return the difference between the average population size and 
#20, which is the population size we expect at open access equilibrium. In this case f.oa = 0.4003154. This mean that with f=f.oa equilibrium population size will be at 20% of K. 
p0 = 0.5
fit = optim(p0, mpa.model, method = c("L-BFGS-B"), lower = 0, upper = 1, 
            growth=0.5, K=100, N0=50, t=50, MPA=0, L = 100, d=0.2)

f.oa = fit$par
f.oa
```

```{r}
#Mpa model
mpa.model = function(f, growth, K, N0, t, d, MPA, L){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
   #MPAs in the middle
  f.patches=rep(f, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.patches[mpa.begin:mpa.end] = 0
  }
  
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Create a vector to store total yield
  total.yield = pop*f.patches
  
  #Create an empty plot to plot the revenue trhough time 
  #plot(NA, NA, ylab="Revenue", xlab="time", ylim=c(0, 100000), xlim=c(0, t))
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    #Immi = c(pop[2]*d/2, c(pop[1:(L-1)]*d/2 + pop[3:L]*d/2), pop[L-1]*d/2)
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #fishing
    fishing = f.patches*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    
  }
  #Create a variable for our resulting population size (all patches in year t)
  sum.pop = sum(pop)
  
  #Create a variable for our resulting yield (all patches in year t)
  sum.yield.eq = sum(fishing)
  
  #Create a variable for our resulting yield accross all years and patches
  sum.yield = sum(total.yield)
  
  #Calculate average population size
  EqB = sum(pop)/L
  
  #return function with main results
  return(c(sum.pop, sum.yield, sum.yield.eq, NPV, MPA, f, d))
  
  #return function for calculating optimal fishing mortality
  #return(sum.yield.eq)
  
  #return function for calculation the open access fishing mortality
  #return(abs(EqB-0.2*K))
  }

####Simulate MPA effectiveness - simulate the optimal MPA size 100 times with randomly assigned MPA location. 
mpa.sim = 0:99
for(i in 1:length(mpa.sim)){
  res = mpa.model(g=0.5, K=100, N0=50, t=50, MPA=mpa.sim[i], L = 100, d=0.2, f=f.oa)
  if(i==1){out=res}else{out=rbind(out, res)}
}
plot(out[,3]~out[,5], ylab="Yield", xlab="MPA size", main="Open Acess fishing mortality")

#Optimal MPA size
out[match(max(out[,3]), out[,3]), 5] 

####Simulate MPA effectiveness - simulate the optimal MPA size 100 times with randomly assigned MPA location. 
mpa.sim = 0:99
for(i in 1:length(mpa.sim)){
  res = mpa.model(g=0.5, K=100, N0=50, t=50, MPA=mpa.sim[i], L = 100, d=0.2, f=f.wm)
  if(i==1){out=res}else{out=rbind(out, res)}
}
plot(out[,3]~out[,5], ylab="Yield", xlab="MPA size", main="Optimal fishing mortality")

#Optimal MPA size
out[match(max(out[,3]), out[,3]), 5] 

```

```{r}
mpa.model = function(f, growth, K, N0, t, d, MPA, L, rand){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
  if(rand=="yes"){
    f.patches=rep(f, L)
    f.patches[round(runif(MPA, 1, 100))]=0
  }else{
  #MPAs in the middle
  f.patches=rep(f, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.patches[mpa.begin:mpa.end] = 0
  }
  }
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Create a vector to store total yield
  total.yield = pop*f.patches
  
  #Create an empty plot to plot the revenue trhough time 
  #plot(NA, NA, ylab="Revenue", xlab="time", ylim=c(0, 100000), xlim=c(0, t))
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    #Immi = c(pop[2]*d/2, c(pop[1:(L-1)]*d/2 + pop[3:L]*d/2), pop[L-1]*d/2)
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #fishing
    fishing = f.patches*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
  
  }
  #Create a variable for our resulting population size (all patches in year t)
  sum.pop = sum(pop)
  
  #Create a variable for our resulting yield (all patches in year t)
  sum.yield.eq = sum(fishing)
  
  #Create a variable for our resulting yield accross all years and patches
  sum.yield = sum(total.yield)
  
  #Calculate average population size
  EqB = sum(pop)/L
  
  #return function with main results
  return(c(sum.pop, sum.yield.eq, sum.yield, MPA, f, d))
  
  #return function for calculating optimal fishing mortality
  #return(sum.yield.eq)
  
  #return function for calculation the open access fishing mortality
  #return(abs(EqB-0.2*K))
  }

#Test our function
res = mpa.model(g=0.5, K=100, N0=50, t=50, MPA=30, L = 100, d=0.2, f=0.4, rand="yes")
res


####Simulate MPA effectiveness - simulate the optimal MPA size 100 times with randomly assigned MPA location. 
mpa.sim = 0:99
for(k in 1:100){
for(i in 1:length(mpa.sim)){
  res = mpa.model(g=0.5, K=100, N0=50, t=50, MPA=mpa.sim[i], L = 100, d=0.2, f=f.oa, rand="yes")
  if(i==1){out=res}else{out=rbind(out, res)}
}
  if(k==1){output=out[match(max(out[,3]), out[,3]), 4]}else{output=rbind(output, out[match(max(out[,3]), out[,3]), 4])}  
}

#Create a boxplot of the optimal MPA size for all 100 simulations of MPA design
boxplot(output, ylab="Optimal mpa size")
```
***b***)

```{r}
###Create our mpa model function
mpa.model = function(q, growth, K, N0, t, d, MPA, L, rand){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
  #First we need to create a vector of length L where areas open to fishing have a value of 1 and areas assigned as MPAs have a value of 0.
  #randomly located MPAs
  if(rand=="yes"){
  f.mpa = rep(1, L)
  f.mpa[round(runif(MPA, 0, 100))]=0}else{
  
  #MPAs in the middle
  f.mpa=rep(1, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.mpa[mpa.begin:mpa.end] = 0
  }
  }
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  total.yield = rep(0, L)
  yield.NPV=0
  profit.NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #Now we calculate distribute the total effort based on abundance (according to Hilborn et al 2006)
    #We first need to create a vector with proportinal abundances on the patches open to fishing. 
    if(sum(f.mpa)==0){prop=rep(0, L)}else{prop = f.mpa*exp(-(1-pop*f.mpa/max(pop*f.mpa)))}
    
    #Next we need to distribute effort based on the proportinal abundances in the patches open to fishing. 
    if(sum(f.mpa)==0){f=rep(0, L)}else{f = 1-exp(-q*(prop/sum(prop)))}
    
    #Now we can just use the vector f we created above to fish our population! 
    #fishing
    fishing = f*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    }
  #PLot fishing mortality in each patch
  plot(f, type="l", ylab="fishing mortality", xlab="patch")
  
  sum.pop = sum(pop)
  sum.yield.eq = sum(fishing)
  sum.yield = sum(total.yield)
  EqB = sum(pop)/L
  #return(c(sum.pop, sum.yield.eq, yield.NPV, MPA, q, d))
  #return(abs(EqB-20))
  return(sum.yield.eq)
}

#Test our function
res = mpa.model(g=0.5, K=100, N0=20, t=50, MPA=20, L = 100, d=0.2, q=50, rand="no")
res
```
Now lets find the the optimal effort

```{r}
mpa.model = function(q, growth, K, N0, t, d, MPA, L, rand){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
    #First we need to create a vector of length L where areas open to fishing have a value of 1 and areas assigned as MPAs have a value of 0.
  #randomly located MPAs
  if(rand=="yes"){
  f.mpa = rep(1, L)
  f.mpa[round(runif(MPA, 0, 100))]=0}else{
  
  #MPAs in the middle
  f.mpa=rep(1, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.mpa[mpa.begin:mpa.end] = 0
  }
  }
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  total.yield = rep(0, L)
  yield.NPV=0
  profit.NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #Effort based on abundance

    #Now we calculate distribute the total effort based on abundance (according to Hilborn et al 2006)
    #We first need to create a vector with proportinal abundances on the patches open to fishing. 
    if(sum(f.mpa)==0){prop=rep(0, L)}else{prop = f.mpa*exp(-(1-pop*f.mpa/max(pop*f.mpa)))}
    
    #Next we need to distribute effort based on the proportinal abundances in the patches open to fishing. 
    if(sum(f.mpa)==0){f=rep(0, L)}else{f = 1-exp(-q*(prop/sum(prop)))}
    
    #Now we can just use the vector f we created above to fish our population! 
    #fishing
    fishing = f*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    }
  #PLot fishing mortality in each patch
  #plot(f, type="l", ylab="fishing mortality", xlab="patch")
  
  sum.pop = sum(pop)
  sum.yield.eq = sum(fishing)
  sum.yield = sum(total.yield)
  EqB = sum(pop)/L
  #return(c(sum.pop, sum.yield.eq, yield.NPV, MPA, q, d))
  #return(abs(EqB-20))
  return(sum.yield.eq)
}

#Find optimal effort to maximize yield. we will be optimizing total yield, by changing total effort (q). In this case optimal effort will be (q=28.76)
p0=c(20)
fit = optim(p0, mpa.model, method = c("L-BFGS-B"), lower=0,upper=100, control = list(fnscale = -1), 
            MPA=0, growth=0.5,
            K=100, t=50, d=0.2, L=100, N0=50, rand = "yes")
q.wm = fit$par
q.wm
```
Now lets find the open access effort
```{r}
mpa.model = function(q, growth, K, N0, t, d, MPA, L, rand){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
    #First we need to create a vector of length L where areas open to fishing have a value of 1 and areas assigned as MPAs have a value of 0.
  #randomly located MPAs
  if(rand=="yes"){
  f.mpa = rep(1, L)
  f.mpa[round(runif(MPA, 0, 100))]=0}else{
  
  #MPAs in the middle
  f.mpa=rep(1, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.mpa[mpa.begin:mpa.end] = 0
  }
  }
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  total.yield = rep(0, L)
  yield.NPV=0
  profit.NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #Effort based on abundance

    #Now we calculate distribute the total effort based on abundance (according to Hilborn et al 2006)
    #We first need to create a vector with proportinal abundances on the patches open to fishing. 
    if(sum(f.mpa)==0){prop=rep(0, L)}else{prop = f.mpa*exp(-(1-pop*f.mpa/max(pop*f.mpa)))}
    
    #Next we need to distribute effort based on the proportinal abundances in the patches open to fishing. 
    if(sum(f.mpa)==0){f=rep(0, L)}else{f = 1-exp(-q*(prop/sum(prop)))}
    
    #Now we can just use the vector f we created above to fish our population! 
    #fishing
    fishing = f*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    }
  #PLot fishing mortality in each patch
  #plot(f, type="l", ylab="fishing mortality", xlab="patch")
  
  sum.pop = sum(pop)
  sum.yield.eq = sum(fishing)
  sum.yield = sum(total.yield)
  EqB = sum(pop)/L
  #return(c(sum.pop, sum.yield.eq, yield.NPV, MPA, q, d))
  return(abs(EqB-20))
  #return(sum.yield.eq)
}

##Find the effort that drives the population down to 20% of K. In this case - q=51.08
p0=c(50)
fit=optim(p0, mpa.model, method = c("Brent"), lower=0,upper=100, MPA=0, growth=0.5,
          K=100, t=50, d=0.2, L=100, N0=20, rand = "yes")
q.oa = fit$par
q.oa
```

Now lets simulate MPA effectiveness
```{r}
mpa.model = function(q, growth, K, N0, t, d, MPA, L, rand){
  
  #Create a vector of fishing mortalities
  #f.patches = c(rep(0, MPA), rep(f, L-MPA))
  
    #First we need to create a vector of length L where areas open to fishing have a value of 1 and areas assigned as MPAs have a value of 0.
  #randomly located MPAs
  if(rand=="yes"){
  f.mpa = rep(1, L)
  f.mpa[round(runif(MPA, 0, 100))]=0}else{
  
  #MPAs in the middle
  f.mpa=rep(1, L)
  if(MPA>0){
    mpa.begin = round((L-MPA)/2) + 1
    mpa.end = mpa.begin + MPA - 1
    f.mpa[mpa.begin:mpa.end] = 0
  }
  }
  #Create a vector for pop
  pop = rep(0, L)
  total.yield = rep(0, L)
  total.yield = rep(0, L)
  yield.NPV=0
  profit.NPV = 0
  
  #Set initial population sizes
  pop[] = N0
  
  #Run a loop over all time steps
  for(n in 2:t){
    
    #population growth
    surplus = growth*pop*(1-pop/K)
    
    #Emigration
    Emi = c(pop[1]*d/2, pop[2:(L-1)]*d, pop[L]*d/2)
    
    #Immigration
    Immi = c(pop[2:L]*d/2, 0) + c(0, pop[1:(L-1)]*d/2)
    
    #Effort based on abundance

    #Now we calculate distribute the total effort based on abundance (according to Hilborn et al 2006)
    #We first need to create a vector with proportinal abundances on the patches open to fishing. 
    if(sum(f.mpa)==0){prop=rep(0, L)}else{prop = f.mpa*exp(-(1-pop*f.mpa/max(pop*f.mpa)))}
    
    #Next we need to distribute effort based on the proportinal abundances in the patches open to fishing. 
    if(sum(f.mpa)==0){f=rep(0, L)}else{f = 1-exp(-q*(prop/sum(prop)))}
    
    #Now we can just use the vector f we created above to fish our population! 
    #fishing
    fishing = f*pop
    
    #update our population size
    pop = pop + surplus - fishing - Emi + Immi
    
    #sum of yield
    total.yield = total.yield + fishing
    
    }
  #PLot fishing mortality in each patch
  #plot(f, type="l", ylab="fishing mortality", xlab="patch")
  
  sum.pop = sum(pop)
  sum.yield.eq = sum(fishing)
  sum.yield = sum(total.yield)
  EqB = sum(pop)/L
  return(c(sum.pop, sum.yield.eq, MPA, q, d))
  #return(abs(EqB-20))
  #return(sum.yield.eq)
}

####Simulate MPA effectiveness for open access effort
mpa.vec = 0:99
for(j in 1:100){
  for(i in 1:length(mpa.vec)){
    res = mpa.model(g=0.5, K=100, N0=20, t=50, MPA=mpa.vec[i], L=100, d=0.2, q=51, rand = "yes")
    if(i==1){out=res}else{out=rbind(out, res)}
  }
if(j==1){output = c(out[match(max(out[,2]), out[,2]), 3], max(out[,2]))}else{output=rbind(output, c(out[match(max(out[,2]), out[,2]), 3], max(out[,2])))}
}

boxplot(output[,1], ylab="optimal MPA size")
```



